version: '3'

services:
  cezerin-api:
    image: node:12.16.3
    working_dir: /data
    environment:
      - LANGUAGE=ru
      - JWT_SECRET_KEY=jhasjdkfasljkdf
      - COOKIE_SECRET_KEY=ajsdhfjasdfk
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shop
      - DB_USER=
      - DB_PASS=
      - ASSETS_TYPE=minio
      - ASSETS_BASE_URL=http://localhost:8887
      - MINIO_ACCESS_KEY=minio-access
      - MINIO_SECRET_KEY=minio-secret
      - STORE_BASE_URL=http://localhost
      - ADMIN_BASE_URL=http://localhost:3002
    volumes:
      - ./cezerin2:/data
    depends_on:
      - db
    command: bash -c "npm run compile || true && npm run start"

  cezerin-store:
    image: node:12.16.3
    working_dir: /data
    environment:
      - LANGUAGE=ru
      - JWT_SECRET_KEY=jhasjdkfasljkdf
      - COOKIE_SECRET_KEY=ajsdhfjasdfk
      - API_BASE_URL=http://cezerin-api:3001/api/v1
      - AJAX_BASE_URL=http://cezerin-api:3001/ajax
      - DISABLE_IMAGE_RESIZE=true
    volumes:
      - ./cezerin2-store:/data
    depends_on:
      - cezerin-api
    command: bash -c "npm run build && npm run start"

  cezerin-admin:
    image: node:12.16.3
    working_dir: /data
    environment:
      - LANGUAGE=ru
    volumes:
      - ./cezerin2-admin:/data
    depends_on:
      - cezerin-api
    command: bash -c "npm run build && node ./node_modules/.bin/pm2 serve ./dist 3002 --no-daemon"

  db:
    image: mongo:3.4
    volumes:
      - ./__storage/mongo:/data/db

  minio:
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    volumes:
      - ./__storage/minio-data:/data
      - ./__storage/minio-config:/root/.minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "minio-access"
      MINIO_SECRET_KEY: "minio-secret"
    command: server /data

  nginx:
    image: nginx:alpine
    depends_on:
      - minio
      - cezerin-admin
      - cezerin-api
      - cezerin-store
    ports:
      - 80:80
      - 3001:3001
      - 3002:3002
      - 8887:8887
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./__storage/nginx-cache:/tmp/nginx-images-cache2