version: '3'

services:
  cezerin-api:
    image: node:12.16.3
    working_dir: /data
    environment:
      - LANGUAGE=ru
    ports:
      - 3001:3001
    environment:
      - JWT_SECRET_KEY=jhasjdkfasljkdf
      - COOKIE_SECRET_KEY=ajsdhfjasdfk
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shop
      - DB_USER=
      - DB_PASS=
      - ASSETS_TYPE=minio
      - ASSETS_BASE_URL=http://localhost:9001
      - MINIO_ACCESS_KEY=minio-access
      - MINIO_SECRET_KEY=minio-secret
    volumes:
      - ./cezerin2:/data
    depends_on:
      - db
    command: bash -c "npm run compile || true && node -r esm build/index.js"
    # command: bash -c "npm run compile && node -r esm build/index.js"
    # command: bash -c "rm -rf node_modules && npm i"
    # restart: always

  cezerin-store:
    image: node:12.16.3
    working_dir: /data
    environment:
      - LANGUAGE=ru
      - JWT_SECRET_KEY=jhasjdkfasljkdf
      - COOKIE_SECRET_KEY=ajsdhfjasdfk
      - API_BASE_URL=http://cezerin-api:3001/api/v1
      - AJAX_BASE_URL=http://cezerin-api:3001/ajax
      - DISABLE_IMAGE_RESIZE=true
    volumes:
      - ./cezerin2-store:/data
    ports:
      - 3000:3000
    depends_on:
      - cezerin-api
    command: bash -c "npm run build && node -r esm dist/server/index.js"
    # command: bash -c "rm -rf node_modules && npm i"
    # restart: always

  cezerin-admin:
    image: node:12.16.3
    working_dir: /data
    environment:
      - LANGUAGE=ru
    volumes:
      - ./cezerin2-admin:/data
    ports:
      - 3002:3002
    depends_on:
      - cezerin-api
    command: bash -c "npm run build && node ./node_modules/.bin/pm2 serve ./dist 3002 && tail -f /dev/null"
    # command: bash -c "rm -rf node_modules && npm i && npm install --save pm2"
    # restart: always

  db:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./__storage/mongo:/data/db

  minio:
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    volumes:
      - ./__storage/minio-data:/data
      - ./__storage/minio-config:/root/.minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "minio-access"
      MINIO_SECRET_KEY: "minio-secret"
    command: server /data